### ISSUE TITLE
GAMA hangs immediately on Mac OS Sierra (1.7RC2)

### ISSUE THREAD

**Issue by thorsilver** [gama-platform/gama#2293]
### Expected behavior
The application should run beyond the initial 'confirm your workspace location' dialog box!

### Actual behavior
GAMA opens, asks to confirm location of my workspace, then hangs indefinitely.  This behaviour continues no matter how many times I force-quit and relaunch.  I have never run GAMA before so there is no previous workspace.  I tried creating a folder at the default workspace location, since one didn't exist there, and that didn't change the behaviour either.

Since the software hangs immediately, there are no log files I can upload and I have no idea what the problem is.  I have tried using JDK 8 and 9, and this behaviour happens with both of them.

### System and version 
GAMA 1.7RC2, Mac OS Sierra (10.12.6), JDK 8/9

**Comment by benoitgaudou** [comment]
This issue is definitely link to issue #2289.
It should be fixed with the next release.

**Comment by jldelda** [comment]
I am facing this issue with the Java SDK 1.8.151 (as stated in #2289), working with Gama 1.8 Release Candidate 1 and Gama 1.7 Latest Release. [And MAC OS Sierra of course]

As specified, since the software hangs immediately, there are no log files I can upload and I have no idea what the problem is.

I have also tried changing the name of the .app and no success. Any idea?

**Comment by hqnghi88** [comment]
Hello, may be there is some misundestanding, AFAIK, gama 1.8 release required jdk 1.8 >151 (161 or 172). And there is a hanging bug in Gama 1.7 that should been fixed. So, can you retry with gama 1.8 and jdk 1.8 172?
Cheers.

**Comment by jldelda** [comment]
I tried Gama 1.8 Release Candidate 1 and java jdk 1.8 161 (I could not find 172, only 171).
This is what I got.
<img width="423" alt="screen shot 2018-07-06 at 9 01 51 pm" src="https://user-images.githubusercontent.com/22085053/42405583-ea058bda-8166-11e8-8a75-a6d63369ed6d.png">

**Comment by hqnghi88** [comment]
So... There is a log , what does it say, please?

**Comment by jldelda** [comment]
Ups, sorry, it was a hidden file and I didn´t see it before.

I copy here the last lines:

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-07-06 21:49:30.223
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
	at org.eclipse.osgi.container.Module.doStop(Module.java:634)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 21 more

```

**Comment by hqnghi88** [comment]
Well, full content or just upload here, i supposed to say that java version is still not ok. If you know how to open terminal, type in : 
java -version

**Comment by jldelda** [comment]
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)


[log.txt](https://github.com/gama-platform/gama/files/2172369/log.txt)

**Comment by hqnghi88** [comment]
In case that you did not see the problem with "version" notion, your MacOs have several jdk at same time, i am not expert on macos , but there is a switching method to tell OS to use java 1.8.161 (if you installed it as you said "tried").

**Comment by jldelda** [comment]
I will research to find that switching method. Thanks for the tip. :)

**Comment by jldelda** [comment]
Solved! :) As @hqnghi88 said, Gama 1.8 and jdk 1.8 172 worked in my mac.
For some reason, although java 1.8 was my default java in browser, it wasn´t in the Applications folder.

This link helped me to understand and solve the problem: https://apple.stackexchange.com/questions/324792/how-to-remove-java-10-or-revert-to-the-previous-version 

Thanks again for the support.
