### ISSUE TITLE
Export to KML.gaml error after 5 cycles

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2543]
**Describe the bug**
Run Export to KML.gaml

The kml export works however the simulation doesn't stop in a clean way throwing the following  java error at cycle 5

1 occurence in Simulation 0 at cycle 5: Java error: NoClassDefFoundError
in save kml_export to: 'result.kmz' type: kmz ;
NoClassDefFoundError: de/micromata/opengis/kml/v_2_2_0/Kml$NameSpaceBeautyfier
de.micromata.opengis.kml.v_2_2_0.Kml.createMarshaller(Kml.java:642)
de.micromata.opengis.kml.v_2_2_0.Kml.marshal(Kml.java:682)
de.micromata.opengis.kml.v_2_2_0.Kml.addKmzFile(Kml.java:667)
de.micromata.opengis.kml.v_2_2_0.Kml.marshalAsKmz(Kml.java:769)
msi.gaml.types.GamaKmlExport.saveAsKmz(GamaKmlExport.java:169)
msi.gaml.statements.SaveStatement.exportKMZ(SaveStatement.java:403)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:375)
in agent Simulation 0

**Desktop (please complete the following information):**
 - OS: [e.g. macOS High Sierra]
 - PC Model: [if applicable, can be useful for displays, OpenGL problems)]
 - GAMA version: [e.g. git, 1.7.1, etc.]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by agrignard** [comment]
Unfortunately this is also happening in the GAMA 1.8 RC2 (this is unfortunate because I think the @ptaillandier commit was made before the release no?

````
1 occurence in Simulation 0 at cycle 5: Java error: NoClassDefFoundError
in save kml_export to: 'result.kmz' type: kmz ;
NoClassDefFoundError: de/micromata/opengis/kml/v_2_2_0/Kml$NameSpaceBeautyfier
de.micromata.opengis.kml.v_2_2_0.Kml.createMarshaller(Kml.java:642)
de.micromata.opengis.kml.v_2_2_0.Kml.marshal(Kml.java:682)
de.micromata.opengis.kml.v_2_2_0.Kml.addKmzFile(Kml.java:667)
de.micromata.opengis.kml.v_2_2_0.Kml.marshalAsKmz(Kml.java:769)
msi.gaml.types.GamaKmlExport.saveAsKmz(GamaKmlExport.java:169)
msi.gaml.statements.SaveStatement.exportKMZ(SaveStatement.java:403)
msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:375)
in agent Simulation 0
````

**Comment by hqnghi88** [comment]
BUT, Did the CI build fix this issue?

**Comment by ptaillandier** [comment]
Nope, it is not working with the last version of GAMA 1.8 (continuous build) whereas it works with the git version.
